import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Cuadrantes Diátaxis (espejo del árbol público MkDocs).
const config: SidebarsConfig = {
  docsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default config;
