export const RENTAL_INCOME_LEDGER = Symbol('RENTAL_INCOME_LEDGER');
export const TAX_DECLARATION_SENDER = Symbol('TAX_DECLARATION_SENDER');
export const OWNER_NOTIFIER = Symbol('OWNER_NOTIFIER');
export const TAX_REPORTING_CLOCK = Symbol('TAX_REPORTING_CLOCK');
